FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY app.py .

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["python", "app.py"]
